### ISSUE TITLE
頂点モードで選択した頂点のウエイトがリストされなくなる

### ISSUE THREAD

**Issue by YukiAkatsuki** [ShikouYamaue/SIWeightEditor#1]
## 内容

ある時点から頂点モードで選択した頂点のウエイトがリストされなくなりました。
具体的な挙動は添付の動画をご確認下さい。
https://drive.google.com/open?id=1_Ez1eSB28wLchDIh3gm1rMj12KOh0kTt

## 実行環境
Windows10
Maya2017, 2018

## 試したこと

復旧ができず現象の再現方法を調べることができなかったので以下のことを試しました。

・新規シーンで作成したバインドされたオブジェクトで試す
・SIWeightEditorを削除し、入れ直す
・Mayaのprefsフォルダを削除し、プリファレンスを初期化する

これらを試しても頂点モード時の挙動が直ることはありませんでした。

## 期待される結果
頂点モードで選択した頂点のウエイトがリストされる。

##
p.s. SIWeightEditorとても楽しく使用させていただいています。手元の環境で本現象からの復旧が出来ないため使用することができなくなってしまっています…。どうぞよろしくお願い致します。

**Comment by YukiAkatsuki** [comment]
https://drive.google.com/open?id=19Bg5iQBdz9NdhrQf_Ie0W6wlX88IHDtM
以下の操作を実行した時のスクリプトエディタログのキャプチャです。

ウィンドウメニューからSIWeightEditor1.1.7を起動
スキンメッシュ[M_body]をオブジェクト選択
頂点モードに切り替え
[M_body]の適当な頂点を選択

**Comment by ShikouYamaue** [comment]
Focus Button　を押すことで解決
